version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: milkguard_user
      POSTGRES_PASSWORD: milkguard_password
      POSTGRES_DB: milkguard_db
      POSTGRES_MULTIPLE_DATABASES: milkguard_db,mlflow_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U milkguard_user -d milkguard_db && pg_isready -U milkguard_user -d mlflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/artifacts/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --registry-store-uri sqlite:////mlflow/artifacts/mlflow.db
      --host 0.0.0.0
    volumes:
      - mlflow_artifacts:/mlflow/artifacts

  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://milkguard_user:milkguard_password@postgres:5432/milkguard_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=supersecretjwtkey_change_me_in_prod
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ML_SERVICE_URL=http://ml-service:8001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app # For hot reloading during dev

  ml-service:
    build:
      context: ./ml-service
    ports:
      - "8001:8001"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_started
    volumes:
      - ./ml-service:/app

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  postgres_data:
  redis_data:
  mlflow_artifacts:
